# **04. Linear Regression with nn.Module**
* 파이토치에서 이미 **구현되어 제공되는 함수**를 불러오는 것으로 쉽게 선형회귀모델을 구현. 
* 파이토치에서 사용
  * 선형 회귀 모델: `nn.Linear()`
  * 평균 제곱오차: `nn.functional.mse_loss()`

## **1. 단순 선형 회귀 구현하기**
### **(1) 필요한 패키지 import 및 초기화**

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

### **(2) 훈련데이터 선언**

In [4]:
#w=2, b=0인 모델
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

* 예측 모델의 가중치(w)를 2, 편향(b)을 0으로 고정하였음. 

### **(3) 훈련데이터 선언**

In [5]:
# 모델을 선언 및 초기화
model=nn.Linear(1,1)

* 하나의 입력 $x$에 대해서 하나의 출력 $y$를 예측하는 모델
* input_dim은 1, output_dim은 1

In [6]:
print(list(model.parameters())) #랜덤 초기화 됨 

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


* `model.parameters` 함수로 모델의 가중치(`w`)와 편향(`b`)을 확인할 수 있음. 

### **(4) 최적화: 경사하강법으로**

In [8]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

nb_epochs=2000
for epoch in range(nb_epochs+1):
    # H(x)
    prediction=model(x_train)
    
    #cost
    cost=F.mse_loss(prediction,y_train) # 파이토치에서 제공하는 평균 제곱 오차 함수 

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward() 
    optimizer.step()
    
    if epoch % 100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


## **2. 다중 선형 회귀 구현하기**
* 다중선형회귀모델을 구현하는 것으로, 3개의 입력과 1개의 출력이 있음. 
* 가설 수식
  * 3개의 `x`로부터 1개의 `y`를 예측하는 문제
  * 수식: $H(x)=w_1x_1+w_2x_2+w_3x_3+b$
  
### **(1) 필요한 패키지 import 및 초기화**

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [10]:
torch.manual_seed(1)

### **(2) 훈련데이터 선언**

In [11]:
#데이터
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

### **(3) 모델 선언 및 초기화**

In [12]:
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


### **(4) 최적화: 경사하강법으로**
#### **(4-1) optim 선언**

In [13]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

#### **(4-2) 최적화**

In [14]:
nb_epochs=2000
for epoch in range(nb_epochs+1):

    #H(x)
    prediction=model(x_train) 
    # (동일) prediction=model.forward(x_train)

    #cost
    cost=F.mse_loss(prediction,y_train) # 파이토치에서 제공하는 평균 제곱 오차 함수

    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


### **(5) 모델 테스트 및 파라메터 확인**
#### **(5-1) 모델 테스트**

In [15]:
# 임의의 입력 [73,80,75] 선언
new_var=torch.FloatTensor([[73,80,75]])
# 입력한 값에 대한 예측값을 pred_y에 저장
pred_y=model(new_var)
print('훈련 후 입력이 [73,80,75]일때의 예측값:',pred_y)

훈련 후 입력이 [73,80,75]일때의 예측값: tensor([[151.2306]], grad_fn=<AddmmBackward0>)


* [73,80,75]의 임의의 입력을 넣어 `pred_y` 값 확인
* 해당 임의의 입력은 훈련에 사용되었던 데이터로 당시 y값 152와 비교하면 근사한 값을 예측했음을 알 수 있음. 
#### **(5-2) 파라메터 확인**

In [16]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
