## **03. XOR 문제 - 단층 퍼셉트론 구현하기**
---

### **(01) pytorch로 단층 퍼셉트론 구현하기**

In [1]:
import torch

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [4]:
# XOR 문제에 대항되는 입력과 출력 

x = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]]).to(device)
y = torch.FloatTensor([[0],[1],[1],[0]]).to(device)

In [7]:
# nn layers

linear1 = torch.nn.Linear(2,2, bias = True)
linear2 = torch.nn.Linear(2,1, bias = True)
sigmoid = torch.nn.Sigmoid() # 활성 함수 

In [8]:
# model 

model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid).to(device)

* 0 또는 1을 예측하는 이진분류문제이므로 비용함수로는 크로스 엔트로피 함수를 사용 
* `nn.BCELoss()`는 이진 분류에서 사용하는 크로스 엔트로피 함수 

In [10]:
# 비용함수와 옵티마이저 정의 

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 1)

In [13]:
# 10,000번 에포크 사용

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(x)

    # 비용함수 
    cost = criterion(hypothesis, y)
    cost.backward()
    optimizer.step()

    if step % 100 == 0: # 100번 에포크마다 비용 출력 
        print(f"{step} epoch: {cost.item()} Cost")

0 epoch: 0.34716302156448364 Cost
100 epoch: 0.3471565246582031 Cost
200 epoch: 0.347150057554245 Cost
300 epoch: 0.34714367985725403 Cost
400 epoch: 0.3471377491950989 Cost
500 epoch: 0.3471316695213318 Cost
600 epoch: 0.34712573885917664 Cost
700 epoch: 0.3471199870109558 Cost
800 epoch: 0.34711408615112305 Cost
900 epoch: 0.3471085727214813 Cost
1000 epoch: 0.3471029996871948 Cost
1100 epoch: 0.347097784280777 Cost
1200 epoch: 0.3470924496650696 Cost
1300 epoch: 0.34708744287490845 Cost
1400 epoch: 0.3470822274684906 Cost
1500 epoch: 0.3470775783061981 Cost
1600 epoch: 0.3470726013183594 Cost
1700 epoch: 0.34706801176071167 Cost
1800 epoch: 0.34706324338912964 Cost
1900 epoch: 0.34705859422683716 Cost
2000 epoch: 0.34705421328544617 Cost
2100 epoch: 0.3470497131347656 Cost
2200 epoch: 0.347045361995697 Cost
2300 epoch: 0.34704113006591797 Cost
2400 epoch: 0.3470368981361389 Cost
2500 epoch: 0.34703290462493896 Cost
2600 epoch: 0.34702882170677185 Cost
2700 epoch: 0.3470247983932495 

### **(02) 학습된 단층 퍼셉트론의 예측값 확인하기**

In [16]:
with torch.no_grad():
    hypothesis = model(x)
    predicted = (hypothesis > 0.5).float()

    acc = (predicted == y).float().mean()

    print(f'모델의 출력값 \n {hypothesis.detach().cpu().numpy()}')
    print(f'모델의 예측값 \n {predicted.detach().cpu().numpy()}')
    print(f'실제값 \n {y.cpu().numpy()}')
    print(f'정확도 \n {acc.item()}')

모델의 출력값 
 [[2.7531455e-04]
 [4.9987873e-01]
 [9.9970007e-01]
 [5.0014031e-01]]
모델의 예측값 
 [[0.]
 [0.]
 [1.]
 [1.]]
실제값 
 [[0.]
 [1.]
 [1.]
 [0.]]
정확도 
 0.5
