## 2. 넘파이로 텐서 만들기
### 벡터와 행렬

In [1]:
import numpy as np

numpy로 텐서 만들기 : (1) 숫자로 이루어진 리스트 선언 (2) np.array()로 감싸주기

### 1) 1D with Numpy

In [2]:
t=np.array([0.,1.,2.,3.,4.,5.,6.]) 
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ',t.ndim) # 차원
print('Shape of t: ',t.shape) # 크기 

Rank of t:  1
Shape of t:  (7,)


* ndim: 몇 차원인지 출력, 1차원은 벡터, 2차원은 행렬, 3차원은 3차원 텐서
* shape: 크기 (7,)=(1,7)=(1 x 7)

In [4]:
print('t[0] t[1] t[-1] = ', t[0],t[1],t[-1]) #인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


* 인덱스를 통해 원소에 접근할 수 있음. 
* (slicing) 범위를 지정하여 원소를 불러옴. 
    * [시작 번호: 끝 번호]: 시작번호<= i < 끝번호

In [6]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # [시작 번호: 끝 번호]로 범위 지정을 통해 접근할 수 있음. 
print('t[:2] t[3:] = ', t[:2],t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2) 2D with Numpy

In [7]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


* .ndim: 몇 차원인지 출력. 1차원 텐서: 벡터, 2차원: 행렬, 3차원: 3차원 텐서 
* .shape: 크기를 출력. (4,3)=(4 x 3): 4행 3열

## 3. 파이토치 텐서 선언하기(Pytorch Tensor Allocation)

In [1]:
import torch