### 4) View: 원소의 수를 유지하면서 텐서의 크기 변경
* numpy에서 reshape와 같은 역할
* 텐서의 크기를 변경해주는 역할

In [4]:
import numpy as np
import torch

In [6]:
t=np.array([[[0,1,2],
             [3,4,5]],
             [[6,7,8],
             [9,10,11]]])

ft=torch.FloatTensor(t)

In [7]:
print(ft.shape)

torch.Size([2, 2, 3])


### 4-1) 3차원 텐서에서 2차원 텐서로 변경

In [8]:
print(ft.view([-1,3])) #ft라는 텐서를 (?,-3)의 크기로 변경
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


* view([-1,3])의 의미
    * -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토피에 맡기겠다는 의미
    * 3은 두번째 차원의 길이는 3을 가지라는 의미 
    * **3차원 텐서를 2차원 텐서로 변경하되 (?,3)의 크기로 변경하라는 의미**
    * (2,2,3) -> (2*2,3) -> (4,3)
* 규칙
    * view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지됨
    * 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추함 
        * (2* 2 *3)=12였으니, (?*3)=12가 되는 ?=4

### 4-2) 3차원 텐서의 크기 변경
* 3차원 텐서에서 차원은 유지하되(3차원), 크기(shape)를 바꾸는 작업
* (2 * 2* 3)=(? * 1 * 3)=12를 만족해야 하므로 ?는 4가 됨

In [9]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 5) 스퀴즈(Squeeze) - 1인 차원을 제거한다. 
* 스퀴즈는 차원이 1인 경우에는 해당 차원을 제거함. 

In [10]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 6) 언스퀴즈(Unsqueeze) -특정 위치에 1인 차원을 추가
* 특정 위치에 1인 차원을 추가

In [13]:
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0)) # 첫번째 차원에 1인 차원 추가
print(ft.unsqueeze(0).shape)

* 인덱스는 0부터 시작하므로 첫번째 차원을 뜻하는 0을 인자로 둠.
* (3,)의 크기를 가졌던 1차원 벡터가 (1,3)의 2차원 텐서로 변경

In [14]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape) 

tensor([[0., 1., 2.]])
torch.Size([1, 3])


* view에서 (1,-1)을 인자로 사용하여 차원 추가

In [15]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


* unsqueeze함수에 1을 인자로 넣으면 두번째 차원을 의미하므로, 2번째 차원에 1을 추가한다는 의미
* 1차원에 해당하는 벡터에 2번째 차원을 넣는 것

In [16]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


* unsqueeze의 인자로 -1을 넣었음. 
* -1은 인덱스 상으로 마지막 차원을 의미함 
* view(), squeeze(), unsqueeze()는 텐서의 원소수를 그대로 유지하면서 모양과 차원을 조절함
### 7) 타입캐스팅(Type Casting)

In [19]:
lt=torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float()) 

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


* .flot()을 붙이면 float형으로 타입 변경

In [21]:
bt=torch.ByteTensor([True,False,False,True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


* .long()이라고 하면 long 타입의 텐서로 변경
* .float()이라고 하면 float 타입의 텐서로 변경

### 8) 연결하기(concatenate)

In [22]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [24]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


* dim=0
    * (2 * 2) 텐서가 (4 * 2) 텐서로 변환
* dim=1
    * (2 * 2) 텐서가 (2 * 4) 텐서로 변환

### 9) 스택킹(Stacking)
* 연결을 하는 또다른 방식: Stacking(스택킹)

In [26]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [27]:
print(torch.stack([x,y,z]))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


* 위의 두 함수 결과는 같으며 작동 원리는 다음과 같음. 
    * x,y,z는 기존에는 전부 (2,)의 크기를 가졌음. 
    * .unsqueeze(0)으로 (1,2)의 크기를 가진 2차원 텐서로 변경
    * .cat을 통해 연결하면 (3 * 2)의 텐서가 됨. 

In [29]:
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 10) ones_like 와 zeros_like
* 1로 채워진 텐서와 0으로 채워진 텐서

In [32]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [33]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


* ones_like
    * 입력 텐서와 동일한 크기를 갖는 1로 이루어진 텐서 생성 
* zeros_like
    * 입력 텐서와 동일한 크기를 갖는 0으로 이루어진 텐서 생성 

### 11) In-place Operation(덮어쓰기 연산)

In [36]:
x=torch.FloatTensor([[1,2],[3,4]])

In [37]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [38]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


* mul은 곱하기 2가 수행된 결과를 보여주지만 텐서의 값이 변하지 않음. 
* _mul은 텐서에 곱하기 2를 수행한 후, **기존값에 덮어쓰기**를 함. 