# 2. 넘파이로 텐서 만들기
## 벡터와 행렬

In [1]:
import numpy as np

numpy로 텐서 만들기 : (1) 숫자로 이루어진 리스트 선언 (2) np.array()로 감싸주기

## 1) 1D with Numpy

In [2]:
t=np.array([0.,1.,2.,3.,4.,5.,6.]) 
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ',t.ndim) # 차원
print('Shape of t: ',t.shape) # 크기 

Rank of t:  1
Shape of t:  (7,)


* ndim: 몇 차원인지 출력, 1차원은 벡터, 2차원은 행렬, 3차원은 3차원 텐서
* shape: 크기 (7,)=(1,7)=(1 x 7)

In [4]:
print('t[0] t[1] t[-1] = ', t[0],t[1],t[-1]) #인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


* 인덱스를 통해 원소에 접근할 수 있음. 
* (slicing) 범위를 지정하여 원소를 불러옴. 
    * [시작 번호: 끝 번호]: 시작번호<= i < 끝번호

In [6]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # [시작 번호: 끝 번호]로 범위 지정을 통해 접근할 수 있음. 
print('t[:2] t[3:] = ', t[:2],t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


## 2) 2D with Numpy

In [7]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ',t.shape)

Rank of t:  2
Shape of t:  (4, 3)


* .ndim: 몇 차원인지 출력. 1차원 텐서: 벡터, 2차원: 행렬, 3차원: 3차원 텐서 
* .shape: 크기를 출력. (4,3)=(4 x 3): 4행 3열

# 3. 파이토치 텐서 선언하기(Pytorch Tensor Allocation)

In [1]:
import torch

## 1) 1D with Pytorch

In [2]:
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [4]:
# 1차원 텐서, 7개 원소
print(t.dim()) # rank (차원)
print(t.shape) # shape
print(t.size()) #shape

1
torch.Size([7])
torch.Size([7])


In [5]:
print(t[0],t[1],t[-1]) # 인덱스로 접근
print(t[2:5],t[4:-1]) # 슬라이싱
print(t[:2],t[3:]) # 슬라이싱 

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2) 2D with Pytorch

In [6]:
t=torch.FloatTensor([[1.,2.,3.],
                    [4.,5.,6.,],
                    [7.,8.,9.,],
                    [10.,11.,12.]])

print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [7]:
# 2차원 (4,3) 크기의 텐서
print(t.dim()) # rank, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [8]:
print(t[:,1]) #  첫번째 차원을 전체 선택, 두번째 차원은 첫번째 것만 가져옴
print(t[:,1].size()) 

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


* 첫번째 차원을 전체 선택
* 두번째 차원의 1번 인덱스 값만을 가져옴 
* 텐서에서 두번째 열에 있는 모든 값을 가져온 상황

In [9]:
print(t[:,:-1]) # 첫번째 차원을 전체 선택, 두번째 차원은 맨 마지막에서 첫번째를 제외하고 가져오는 경우 

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 3) 브로드캐시팅(Broadcasting)
* 두 행렬 A,B가 있다고 가정,각 행렬 간의 사칙연산을 위해서는 다음의 조건이 있음. 
    * (덧셈과 뺄셈) 두 행렬 A,B의 크기가 같아야함. 
    * (곱셈) A의 마지막 차원과 B의 마지막 차원이 같아야함. 
* 딥러닝을 하게 될때 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙연산을 수행할 수 있음. 
* 이를 위해 파이토치에서는 **자동으로 크기를 맞춰서 연산을 수행하는 브로드캐스팅 기능**을 제공. 

In [11]:
# 크기가 (1,2)로 같은 행렬간의 덧셈 연산
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [12]:
# Vector + Scalar
m1=torch.FloatTensor([1,2])
m2=torch.FloatTensor([3]) # [3] -> [3,3] (브로드캐스팅)
print(m1+m2)

tensor([4., 5.])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
print(m1+m2) 

* 브로드캐스팅 과정에서 두 텐서는 다음과 같이 변경됨. 
    * [[1,2],[1,2]]
    * [[3,3],[4,4]]
* 자동으로 텐서의 크기를 변화시켜주어 편리하지만, 원하는 결과가 나오지 않을 수 있으므로 주의해서 사용해야함. 

## 4) 자주 사용되는 기능들
### [1] 행렬 곱셈과 곱셈의 차이 (Matrix Multiplication vs Multiplication)
* .matmul 행렬 곱셈
* .mul 곱셈

In [13]:
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ',m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


* element-wise 곱셈이 존재함. 
* 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 말함

In [14]:
m1=torch.FloatTensor([[1,2],[3,4]])
m2=torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


* 위의 두가지 곱셈에서 m2는 다음의 행렬로 브로드캐시틍이 된 후에 곱셈이 수행됐음. 
    * [1]   
      [2]    
      ==> [[1,1],            
                [2,2]]     

### [2] 평균(Mean)

In [15]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [16]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [17]:
print(t.mean(dim=0))

tensor([2., 3.])


* dim=0이라는 것은 첫번째 차원을 의미함. (행)
* 인자로 dim을 준다면 해당 차원을 제거한다는 뜻이 됨 -> 행열에서 '열' 만 남게 됨. 
* 실제 연산 과정
    t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.   
    [[1., 2.],  
     [3., 4.]]   
    1과 3의 평균을 구하고, 2와 4의 평균을 구한다.    
    결과 ==> [2., 3.]   

In [18]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


### [3] 덧셈(Sum)

In [19]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### [4] 최대(Max)와 아그맥스(ArgMax)
* Max: 원소의 최대값을 리턴
* ArgMax: 최대값을 가진 인덱스를 리ㅣ턴

In [22]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.max())
print(t.max(dim=0)) # max와 argmax를 모두 return 

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


* max에 dim 인자를 주면 argmax도 함께 리턴함. 
* 최대값(max)와 최대값의 인덱스값(argmax)를 리턴함. 
* max 또는 argmax만 리턴받고 시다면 리턴값에 인덱스를 부여
    * 0법 인덱스: max
    * 1번 인덱스: argmax

In [23]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [24]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
